### ISSUE TITLE
User: View SMS history

### ISSUE THREAD

**Issue by alex2grad** [SythilBlade/sythil-odoo-test#2]
User should has possibility to view own SMS history

**Comment by SythilBlade** [comment]
Good point I'll add a filter to the SMS history that let's a user see only their smses  by default

**Comment by alex2grad** [comment]
I've added a new menu Messaging->SMS->SMS History with a filter.
See my commit 75256843881766e1f742039af9fa990491c4468d

**Comment by SythilBlade** [comment]
Looks like you beat me to it nice job.
